//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string book_id { get; set; }
        public string UID { get; set; }
        public string lot_id { get; set; }
        public byte[] booking_time { get; set; }
        public Nullable<System.DateTime> checkin_time { get; set; }
        public Nullable<System.TimeSpan> release_time { get; set; }
        public Nullable<System.DateTime> checkout_time { get; set; }
    
        public virtual ParkingLot ParkingLot { get; set; }
        public virtual User User { get; set; }
    }
}
