//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public string UID { get; set; }
        public string Name { get; set; }
        public string Plate_n { get; set; }
        public string mobile_n { get; set; }
        public string email { get; set; }
        public string car_model { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
